export const ACTION_GET_CRYPTO_LIST = 'ACTION_GET_CRYPTO_LIST';
export const ACTION_GET_CRYPTO_LIST_SUCCESS = 'ACTION_GET_CRYPTO_LIST_SUCCESS';

export const ACTION_SET_RECORD_VIEW = 'ACTION_SET_RECORD_VIEW';
